# Generated by Django 5.2.3 on 2025-08-30 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createstorevendorform', '0003_alter_userstore_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
