# Generated by Django 5.2.3 on 2025-11-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createstorevendorform', '0004_alter_userstore_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstore',
            old_name='phone_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='userstore',
            old_name='name',
            new_name='days_to_return',
        ),
        migrations.RenameField(
            model_name='userstore',
            old_name='store_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='userstore',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userstore',
            name='store_type',
        ),
    ]
