# Generated by Django 5.2.3 on 2025-11-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createstorevendorform', '0005_rename_phone_number_userstore_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstore',
            name='owner',
        ),
    ]
