# Generated by Django 5.2.3 on 2025-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoress',
            field=models.CharField(choices=[('men', 'men'), ('food', 'food'), ('women', 'women'), ('kids', 'kids'), ('accessories', 'accessories'), ('shoes', 'shoes'), ('bags', 'bags'), ('jewelry', 'jewelry'), ('home', 'home'), ('beauty', 'beauty'), ('مواد التنضيف', 'مواد التنضيف')], default='men', max_length=100),
        ),
    ]
