# Generated by Django 5.2.3 on 2025-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_categoress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs_product',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='products/'),
        ),
    ]
