# Generated by Django 5.2.3 on 2025-08-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_imgs_product_images_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs_product',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
    ]
