# Generated by Django 5.2.3 on 2025-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_imgs_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs_product',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
