# Generated by Django 5.2.3 on 2025-08-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_imgs_product_images_alter_vendor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs_product',
            name='images',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
