# Generated by Django 5.2.3 on 2025-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
