# Generated by Django 5.2.3 on 2025-10-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_category_categoress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='delivry',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
