# Generated by Django 5.2.3 on 2025-10-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cartorder_user_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Unity',
            field=models.CharField(choices=[('Dz', 'Dz'), ('kg', 'kg'), ('g', 'g'), ('قطعة', 'قطعة'), ('دلو', 'دلو'), ('علبة', 'علبة'), ('قارورة', 'قارورة'), ('كيس', 'كيس'), ('رطل', 'رطل'), ('l', 'l'), ('m', 'm')], default='Dz', max_length=10),
        ),
    ]
