# Generated by Django 5.2.3 on 2025-10-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_unity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Unity',
            new_name='unity',
        ),
    ]
