# Generated by Django 5.2.3 on 2025-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_unity_product_unity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unity',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('قطعة', 'قطعة'), ('دلو', 'دلو'), ('علبة', 'علبة'), ('قارورة', 'قارورة'), ('كيس', 'كيس'), ('رطل', 'رطل'), ('l', 'l'), ('m', 'm')], default='kg', max_length=10),
        ),
    ]
