# Generated by Django 5.2.3 on 2025-11-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_unity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descreption',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imge',
        ),
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
    ]
