# Generated by Django 5.2.3 on 2025-11-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_category_descreption_remove_category_imge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VendorCategories', to='core.vendor'),
        ),
    ]
