# Generated by Django 5.2.3 on 2026-01-03 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_cartorder_vendor_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vendor_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorders_new', to='core.vendor'),
        ),
    ]
