# Generated by Django 5.2.3 on 2026-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_cartorder_vendor_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
